In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig

print("Torch:", torch.__version__)
print("Transformers:", __import__("transformers").__version__)
print("TRL:", __import__("trl").__version__)
print("PEFT:", __import__("peft").__version__)
print("bitsandbytes:", __import__("bitsandbytes").__version__)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'Could not load this library: /opt/conda/lib/python3.10/site-packages/torchvision/image.so'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

Torch: 2.9.1+cu128
Transformers: 4.57.3
TRL: 0.25.1
PEFT: 0.18.0
bitsandbytes: 0.48.2
GPU: NVIDIA GeForce RTX 4090

In [ ]:
MODEL_NAME = "Qwen/Qwen2.5-Coder-7B-Instruct"

# 4-bit quantization config (QLoRA)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

print(f"Loading {MODEL_NAME} in 4-bit on CUDA...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="sdpa",
)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

Loading Qwen/Qwen2.5-Coder-7B-Instruct in 4-bit on CUDA...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

In [ ]:
print("Streaming Cosmopedia (stanford subset)...")
from datasets import load_dataset, IterableDataset

raw_stream = load_dataset(
    "HuggingFaceTB/cosmopedia",
    "stanford",
    split="train",
    streaming=True,
)

def is_cs_content(example):
    text = example["text"].lower()
    keywords = [
        "computer science", "algorithm", "python", "machine learning",
        "deep learning", "neural network", "data structure",
        "operating system", "database", "distributed system",
        "graph theory", "complexity", "dynamic programming",
    ]
    ban_list = ["clinical", "physiology", "anatomy", "patient", "disease"]
    if any(b in text for b in ban_list):
        return False
    return any(k in text for k in keywords)

# Filter + enforce pure {"text": str} structure
def cs_generator():
    count = 0
    for ex in raw_stream:
        if not is_cs_content(ex):
            continue
        yield {"text": ex["text"]}
        count += 1
        if count >= 5000:   # cap at 5k examples
            break

train_stream = IterableDataset.from_generator(cs_generator)

print("Dataset stream ready (up to 5k CS examples).")

Streaming Cosmopedia (stanford subset)...

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Dataset stream ready (up to 5k CS examples).

In [ ]:
# Convert the streaming iterable into a list of examples (in memory)
# For 5k items this is fine on your 128 GB RAM
samples = list(train_stream)

print(f"Total filtered CS examples: {len(samples)}\n")

# Print first 10 samples (truncated)
for i, ex in enumerate(samples[:10], start=1):
    text = ex["text"].strip().replace("\n", " ")
    print(f"--- Sample {i} ---")
    print(text[:400] + ("..." if len(text) > 400 else ""))
    print()

Total filtered CS examples: 5000

--- Sample 1 ---
7.2 Dutch Pidgins and Creoles  Introduction  In this section, we will delve into the world of Dutch pidgins and creoles, examining their origins, development, structures, and functions within various communities. We will explore how these languages emerged as contact varieties between Dutch speakers and non-Dutch speaking populations, often under conditions of colonialism, slavery, or trade. Our f...

--- Sample 2 ---
2.3 The Inner Ear  Introduction ---------------------  Welcome to the fascinating world of the inner ear! This complex structure is responsible for our sense of hearing and balance, making it an essential component of our daily lives. Despite its small size (approximately 5mm in diameter), the inner ear contains some of the most intricate structures in the human body. In this section, we will delv...

--- Sample 3 ---
1.2 Importance of Electro-Neural Interfaces  As we delve deeper into the fascinating world of electro-neural interfaces (ENIs), it's essential to understand why they matter so much. ENIs hold immense potential for transforming various aspects of our lives, from healthcare to entertainment and beyond. This section will explore their significance through real-life applications, ethical consideration...

--- Sample 4 ---
Sure thing! Here's a sample sub-unit entitled "4.4. Hands-on Experience with Deploying Machine Learning Models on Embedded Systems." I hope it meets your needs!  ---  Congratulations, young coder! You've made it to Chapter 4.4, where we get to put all our knowledge into practice by deploying real-life machine learning (ML) models onto actual embedded systems! This is going to be fun and exciting, ...

--- Sample 5 ---
1.3 Goals of the Course and Project  Welcome back to our course on Excavating Enslavement! We’ve covered the basics of what this course will entail and why we’re taking a project-based approach. Now let’s dive into the goals of the course and project. This information is crucial as it sets the stage for everything else we will do together. By understanding these objectives, you can better apprecia...

--- Sample 6 ---
6.1 Preparing a Presentation  As a professional or researcher in your field, presenting your work is an essential skill. It allows you to share your findings with colleagues, stakeholders, and the wider academic community. However, creating an effective presentation can be challenging, especially when communicating complex ideas to a sophisticated audience. This section outlines strategies for pre...

--- Sample 7 ---
6.2 Enhancement  Welcome back, dear reader! We hope you've enjoyed our journey through biomedical signal filtering thus far. Now it's time to take things one step further with enhancement techniques. In this section, we will explore how to improve the quality of biomedical signals beyond simple filtering. This process involves analyzing the properties of these signals and applying advanced methods...

--- Sample 8 ---
2.4 Group Dynamics and Team Processes  Introduction  As organizations continue to prioritize teamwork as a means of achieving their goals, understanding group dynamics and team processes has become increasingly important for both practitioners and researchers in organizational behavior. This sub-unit will delve into the classic areas of research within this domain, including group formation, cohes...

--- Sample 9 ---
3.2 Programming Simple Coders  Welcome to Section 3.2 of our comprehensive guide on Perceptual Audio Coding! This section will take a more hands-on approach by introducing you to programming simple audio coders from scratch. By the end of this section, you will have gained valuable insights into the inner workings of audio coding algorithms, enabling you to develop your own basic coder.  **Prerequ...

--- Sample 10 ---
4.2 The Relationship Between Texts and Objects  In this section, we will explore the relationship between texts and objects – two seemingly distinct categories that actually inform and enrich one another in fascinating ways. By examining how ancient artifacts and written records can shed light on each other, we can gain a more nuanced understanding of classical scholarship and the world of the anc...

In [ ]:
from trl import SFTTrainer, SFTConfig

output_dir = "./qwen2_5_coder_cs_agent_lora"

sft_config = SFTConfig(
    output_dir=output_dir,
    dataset_text_field="text",
    max_length=1024,              # was 4096
    per_device_train_batch_size=8,    # was 4
    gradient_accumulation_steps=1,    # was 2
    learning_rate=2e-4,
    max_steps=200,
    logging_steps=10,
    fp16=True,
    bf16=False,
    optim="paged_adamw_8bit",
    report_to="none",
    save_strategy="no",
    packing=False,
)


trainer = SFTTrainer(
    model=model,
    train_dataset=train_stream,
    processing_class=tokenizer,
    args=sft_config,
    # formatting_func removed
)

print("Starting training on RTX 4090...")
trainer.train()

print("Saving LoRA adapter...")
trainer.save_model(output_dir)

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151645}.

Starting training on RTX 4090...

Saving LoRA adapter...

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

MODEL_NAME = "Qwen/Qwen2.5-Coder-7B-Instruct"
ADAPTER_DIR = "./qwen2_5_coder_cs_agent_lora"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print("Loading BASE model (no LoRA)...")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="sdpa",
)
base_model.eval()

print("Loading FINETUNED model (base + LoRA)...")
ft_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="sdpa",
)
ft_model = PeftModel.from_pretrained(ft_model, ADAPTER_DIR)
ft_model.eval()

Device: cuda
Loading BASE model (no LoRA)...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Loading FINETUNED model (base + LoRA)...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(152064, 3584)
        (layers): ModuleList(
          (0-27): 28 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=3584, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=512, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=512, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=512, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=512, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=3584, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
            )
            (mlp): Qwen2MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=18944, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=18944, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=18944, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=18944, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=18944, out_features=3584, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=18944, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((3584,), eps=1e-06)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
    )
  )
)

In [ ]:
def generate_answer(model, prompt, max_new_tokens=2048, temperature=0.2):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=0.9,
            eos_token_id=tokenizer.eos_token_id,
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
prompt = (
    "You are a CS tutor.\n\n"
    "Explain Dijkstra's algorithm step by step and show a Python implementation "
    "for finding the shortest path in a weighted graph."
)

print("=== BASE MODEL ===")
base_out = generate_answer(base_model, prompt)
print(base_out)
print("\n" + "="*80 + "\n")

print("=== FINETUNED (BASE + LoRA) MODEL ===")
ft_out = generate_answer(ft_model, prompt)
print(ft_out)

=== BASE MODEL ===
You are a CS tutor.

Explain Dijkstra's algorithm step by step and show a Python implementation for finding the shortest path in a weighted graph. Dijkstra's algorithm is used to find the shortest paths between nodes in a graph, which can be represented as a set of vertices connected by edges with associated weights. The algorithm works by maintaining a priority queue of vertices, where each vertex has an estimated distance from the source node. Initially, all distances are set to infinity except for the source node, which is set to zero. The algorithm then iteratively selects the vertex with the smallest estimated distance, updates its neighbors' distances if a shorter path is found, and adds them to the priority queue. This process continues until all vertices have been processed or the destination node is reached.
Sure! Let's go through Dijkstra's algorithm step by step and then provide a Python implementation.

### Step-by-Step Explanation of Dijkstra's Algorithm

1. **Initialization**:
   - Create a dictionary `distances` to store the shortest known distance to each vertex. Initialize all distances to infinity (`float('inf')`) except for the source vertex, which should be initialized to 0.
   - Create a dictionary `previous_vertices` to keep track of the shortest path. Initialize it with `None` for all vertices except the source vertex, which should be initialized to itself.
   - Use a priority queue (min-heap) to always select the vertex with the smallest tentative distance.

2. **Algorithm Execution**:
   - While there are vertices in the priority queue:
     - Extract the vertex `u` with the smallest distance from the priority queue.
     - For each neighbor `v` of `u`, calculate the tentative distance from the source to `v` through `u`.
       - If this tentative distance is less than the current known distance to `v`, update the distance to `v` and set `u` as the previous vertex for `v`.
     - Add `v` to the priority queue with its updated distance.

3. **Termination**:
   - When the priority queue is empty, the algorithm terminates. At this point, the `distances` dictionary contains the shortest paths from the source to all other vertices.

### Python Implementation of Dijkstra's Algorithm

Here's a Python implementation using a min-heap from the `heapq` module:

```python
import heapq

def dijkstra(graph, start):
    # Number of vertices in the graph
    n = len(graph)

    # Distances from start to all other vertices
    distances = [float('inf')] * n
    distances[start] = 0

    # Previous vertices on the shortest path
    previous_vertices = [None] * n

    # Priority queue: (distance, vertex)
    priority_queue = [(0, start)]

    while priority_queue:
        # Get the vertex with the smallest distance
        current_distance, current_vertex = heapq.heappop(priority_queue)

        # Nodes can get added to the priority queue multiple times. We only
        # process a vertex the first time we remove it from the priority queue.
        if current_distance > distances[current_vertex]:
            continue

        # Explore each neighbor of the current vertex
        for neighbor, weight in graph[current_vertex]:
            distance = current_distance + weight

            # Only consider this new path if it's better
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                previous_vertices[neighbor] = current_vertex
                heapq.heappush(priority_queue, (distance, neighbor))

    return distances, previous_vertices

# Example usage
graph = {
    0: [(1, 4), (2, 1)],
    1: [(2, 2), (3, 5)],
    2: [(1, 2), (3, 1)],
    3: []
}

start_vertex = 0
distances, previous_vertices = dijkstra(graph, start_vertex)

print("Distances:", distances)
print("Previous Vertices:", previous_vertices)
```

### Explanation of the Code

- **Graph Representation**: The graph is represented as a dictionary where each key is a vertex and the value is a list of tuples representing the neighboring vertices and their corresponding edge weights.
- **Priority Queue**: A min-heap is used to efficiently extract the vertex with the smallest distance.
- **Distance and Previous Vertex Arrays**: These arrays are used to store the shortest distances and the previous vertices on the shortest path, respectively.
- **Main Loop**: The main loop processes each vertex, updating the distances to its neighbors if a shorter path is found.

This implementation will output the shortest distances from the starting vertex to all other vertices in the graph. You can modify the `graph` and `start_vertex` variables to test different scenarios.

================================================================================

=== FINETUNED (BASE + LoRA) MODEL ===
You are a CS tutor.

Explain Dijkstra's algorithm step by step and show a Python implementation for finding the shortest path in a weighted graph. Here is an example of a weighted graph:

```
graph = {
    'A': {'B': 1, 'C': 4},
    'B': {'A': 1, 'C': 2, 'D': 5},
    'C': {'A': 4, 'B': 2, 'D': 1},
    'D': {'B': 5, 'C': 1}
}
```

Sure, let's go through Dijkstra's algorithm step by step and then implement it in Python to find the shortest path in a weighted graph.

### Step-by-Step Explanation of Dijkstra's Algorithm

#### Initialization
1. **Create a set `S`** that will contain all vertices that have been processed (i.e., their shortest paths from the source vertex have been determined).
2. **Assign tentative distances** to each vertex:
   - Set the distance to the source vertex as 0.
   - Set the distance to all other vertices as infinity (`float('inf')`).

3. **Select the source vertex** and add it to the set `S`.

#### Iteration
4. For each vertex `u` not yet in `S`, consider all its neighbors `v`. If adding the edge `(u, v)` results in a shorter path than previously recorded, update the distance to `v`.

5. Once you've considered all neighbors of `u`, move `u` from the unprocessed set to the processed set `S`.

6. Repeat steps 4 and 5 until all vertices are in `S`.

7. The shortest path to any vertex can now be retrieved from the updated distances.

### Example Walkthrough

Let's walk through the algorithm with your provided graph starting at vertex `'A'`.

```python
# Initial setup
graph = {
    'A': {'B': 1, 'C': 4},
    'B': {'A': 1, 'C': 2, 'D': 5},
    'C': {'A': 4, 'B': 2, 'D': 1},
    'D': {'B': 5, 'C': 1}
}

# Initialize distances dictionary
distances = {vertex: float('inf') for vertex in graph}
distances['A'] = 0

# Initialize previous_vertices dictionary to reconstruct the path later
previous_vertices = {vertex: None for vertex in graph}

# Function to find the vertex with minimum distance value
def min_distance_vertex(distances, S):
    min_value = float('inf')
    min_vertex = None
    for vertex, dist in distances.items():
        if dist < min_value and vertex not in S:
            min_value = dist
            min_vertex = vertex
    return min_vertex

# Main loop of Dijkstra's algorithm
S = set()
while len(S) != len(graph):
    u = min_distance_vertex(distances, S)
    S.add(u)

    # Update distances to adjacent vertices
    for neighbor, weight in graph[u].items():
        new_dist = distances[u] + weight
        if new_dist < distances[neighbor]:
            distances[neighbor] = new_dist
            previous_vertices[neighbor] = u

print("Distances:", distances)
print("Previous Vertices:", previous_vertices)
```

### Output Interpretation
After running this code, you get two dictionaries:
- `distances`: Contains the shortest distance from the source ('A') to every other node.
- `previous_vertices`: Helps reconstruct the shortest path by tracing back from each node to its predecessor along the optimal route.

For instance, if we want to know the shortest path from 'A' to 'D', we follow these steps using the `previous_vertices` dictionary:
- Start at 'D'.
- Trace back to its predecessor which is 'C'.
- Continue tracing back to 'C''s predecessor which is 'B'.
- Finally, trace back to 'B''s predecessor which is 'A'.

So, the shortest path from 'A' to 'D' is ['A', 'B', 'C', 'D'].

In [ ]:
import torch, gc

def flush_cuda():
    gc.collect()                 # Python garbage collector
    if torch.cuda.is_available():
        torch.cuda.empty_cache() # Release cached GPU memory
        torch.cuda.ipc_collect() # Cleanup inter-process memory
        torch.cuda.synchronize() # Ensure all pending ops are done

flush_cuda()
print("GPU memory flushed.")

GPU memory flushed.

In [ ]:
from datasets import IterableDataset

SYSTEM_PROMPT = "You are a helpful CS tutor who explains concepts step by step."

def cs_generator_chat():
    # reuse your filtered raw_stream + is_cs_content from before
    count = 0
    for ex in raw_stream:
        if not is_cs_content(ex):
            continue
        content = ex["text"]
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": "Teach me this topic in detail."},
            {"role": "assistant", "content": content},
        ]
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        yield {"text": text}
        count += 1
        if count >= 5000:
            break

tutor_stream = IterableDataset.from_generator(cs_generator_chat)
print(next(iter(tutor_stream))["text"][:400])

<|im_start|>system
You are a helpful CS tutor who explains concepts step by step.<|im_end|>
<|im_start|>user
Teach me this topic in detail.<|im_end|>
<|im_start|>assistant
 7.2 Dutch Pidgins and Creoles

Introduction

In this section, we will delve into the world of Dutch pidgins and creoles, examining their origins, development, structures, and functions within various communities. We will explor

In [ ]:
from trl import SFTTrainer, SFTConfig

output_dir_tutor = "./qwen2_5_coder_cs_tutor_lora"

tutor_cfg = SFTConfig(
    output_dir=output_dir_tutor,
    dataset_text_field="text",
    max_length=1024,          # was 2048/4096
    per_device_train_batch_size=2,# was 4
    gradient_accumulation_steps=1,# was 2
    learning_rate=1e-4,
    max_steps=200,                # smaller sanity run first
    logging_steps=5,
    fp16=True,
    bf16=False,
    optim="paged_adamw_8bit",
    report_to="none",
    save_strategy="no",
    packing=False,
)


tutor_trainer = SFTTrainer(
    model=model,                # your current CS-LoRA model
    train_dataset=tutor_stream,
    processing_class=tokenizer,
    args=tutor_cfg,
)

tutor_trainer.train()
tutor_trainer.save_model(output_dir_tutor)

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

MODEL_NAME = "Qwen/Qwen2.5-Coder-7B-Instruct"
CS_ADAPTER_DIR = "./qwen2_5_coder_cs_agent_lora"
TUTOR_ADAPTER_DIR = "./qwen2_5_coder_cs_tutor_lora"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print("Loading shared 4-bit base model...")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="sdpa",
)
base_model.eval()

/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'Could not load this library: /opt/conda/lib/python3.10/site-packages/torchvision/image.so'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

Device: cuda
Loading shared 4-bit base model...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear4bit(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear4bit(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear4bit(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear4bit(in_features=3584, out_features=3584, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear4bit(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear4bit(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear4bit(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((3584,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
)

In [ ]:
def load_adapter(model, adapter_dir):
    # Clone the base reference so we don't modify original object
    m = model
    m = PeftModel.from_pretrained(m, adapter_dir)
    m.eval()
    return m

def chat_once(model, user_msg, system_msg="You are a helpful CS tutor."):
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer([text], return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=4096,
            do_sample=True,
            temperature=0.2,
            top_p=0.9,
            eos_token_id=tokenizer.eos_token_id,
        )
    return tokenizer.decode(out[0], skip_special_tokens=True)

In [ ]:
prompt = (
    "Explain Dijkstra's algorithm step by step and give a Python "
    "implementation for the shortest path in a weighted graph."
)

print("=== BASE MODEL ===\n")
print(chat_once(base_model, prompt))
print("\n" + "="*80 + "\n")

print("=== CS-SFT LoRA ===\n")
cs_model = load_adapter(base_model, CS_ADAPTER_DIR)
print(chat_once(cs_model, prompt))
del cs_model
torch.cuda.empty_cache()
print("\n" + "="*80 + "\n")

print("=== TUTOR-STYLE LoRA ===\n")
tutor_model = load_adapter(base_model, TUTOR_ADAPTER_DIR)
print(chat_once(tutor_model, prompt))
del tutor_model
torch.cuda.empty_cache()

=== BASE MODEL ===

system
You are a helpful CS tutor.
user
Explain Dijkstra's algorithm step by step and give a Python implementation for the shortest path in a weighted graph.
assistant
Dijkstra's Algorithm is used to find the shortest paths between nodes in a graph, which may represent, for example, road networks. The algorithm works for both directed and undirected graphs as long as all of the edge weights are non-negative.

Here is a step-by-step explanation:

1. Initialize the distance to the source node as 0 and to all other nodes as infinity.
2. Create an empty set S that will contain the visited nodes.
3. While there are unvisited nodes:
   - Pick the unvisited node with the smallest distance value, call it u.
   - Add u to the set S of visited nodes.
   - Update the distance values of the neighbors of u. If v is a neighbor of u and has not been visited yet, then check if the distance from the source to v through u is lower than the current known distance from the source to v. If so, update the distance of v.
4. When the destination node has been visited (or when the smallest tentative distance among the vertices in the queue is infinity), or if the queue is empty (i.e., all nodes have been visited), the algorithm ends. The output is the distance array D, where D[v] contains the shortest path distance from the source to vertex v.

Now let's see how we can implement this algorithm using Python:

```python
import heapq

def dijkstra(graph, start):
    # Initialize distances dictionary with infinite values except for the starting node
    dist = {node: float('inf') for node in graph}
    dist[start] = 0

    # Priority queue to store nodes based on their minimum distance
    pq = [(0, start)]

    while pq:
        # Get the node with the smallest distance value
        current_dist, current_node = heapq.heappop(pq)

        # Nodes can get added to the priority queue multiple times. We only process a vertex the first time we remove it from the priority queue.
        if current_dist > dist[current_node]:
            continue

        # Explore each neighbor of the current node
        for neighbor, weight in graph[current_node].items():
            distance = current_dist + weight

            # Only consider this new path if it's better
            if distance < dist[neighbor]:
                dist[neighbor] = distance
                heapq.heappush(pq, (distance, neighbor))

    return dist


# Example usage:
graph = {
    'A': {'B': 1, 'C': 4},
    'B': {'A': 1, 'C': 2, 'D': 5},
    'C': {'A': 4, 'B': 2, 'D': 1},
    'D': {'B': 5, 'C': 1}
}

print(dijkstra(graph, 'A'))  # Output: {'A': 0, 'B': 1, 'C': 3, 'D': 4}
```

In this code snippet, `graph` represents our input graph as an adjacency list where keys are nodes and values are dictionaries containing neighboring nodes and corresponding edge weights. The function returns a dictionary mapping each node to its shortest path distance from the given source node.

================================================================================

=== CS-SFT LoRA ===

system
You are a helpful CS tutor.
user
Explain Dijkstra's algorithm step by step and give a Python implementation for the shortest path in a weighted graph.
assistant
Dijkstra's Algorithm is used to find the shortest paths between nodes in a graph, which can be represented as a set of edges connecting pairs of vertices or nodes. This algorithm works for both directed and undirected graphs as long as all of the edge weights are non-negative.

Here are the steps involved in Dijkstra's Algorithm:

1. Initialize the distance from the source node to all other nodes as infinity except for the source node itself, which should have a distance of zero.
2. Create an empty set S that will store the visited nodes.
3. Select the unvisited node with the smallest distance value, mark it as visited, and add it to the set S.
4. Update the distance values of its adjacent nodes if they are smaller than the current stored distances.
5. Repeat steps 3-4 until all nodes have been visited.

Python Implementation:
```python
import heapq

def dijkstra(graph, start):
    # initialize distances dictionary with infinite values except for the start node
    distances = {node: float('inf') for node in graph}
    distances[start] = 0

    # create priority queue (min heap) with tuples containing distance and node
    pq = [(0, start)]

    while pq:
        # get the node with minimum distance
        current_dist, current_node = heapq.heappop(pq)

        # skip if we've already processed this node
        if current_dist > distances[current_node]:
            continue

        # check each neighbor of the current node
        for neighbor, weight in graph[current_node].items():
            distance = current_dist + weight

            # only consider this new path if it's better
            if distance < distances[neighbor]:
                distances[neighbor] = distance

                # push the updated distance and neighbor onto the priority queue
                heapq.heappush(pq, (distance, neighbor))

    return distances
```
In this implementation, `graph` is a dictionary where keys represent nodes and values are dictionaries representing their neighbors and corresponding edge weights. The function returns a dictionary containing the shortest distances from the starting node to every other node in the graph.

================================================================================

=== TUTOR-STYLE LoRA ===

system
You are a helpful CS tutor.
user
Explain Dijkstra's algorithm step by step and give a Python implementation for the shortest path in a weighted graph.
assistant
Dijkstra's Algorithm is an algorithm used to find the shortest paths between nodes in a graph, which may represent, for example, road networks. The algorithm works by maintaining two sets of vertices, one set contains vertices whose shortest path from source has been found and another set contains vertices whose shortest path hasn't been found yet.

Here is how it works:

1. Initialize all distances as infinite except the source node which distance will be zero.
2. Pick the vertex with minimum distance value, mark it visited.
3. Update distance value of adjacent vertices of the picked vertex only if the new calculated distance is less than the previously stored distance.
4. Repeat steps 2 & 3 until no more vertices can be processed.

Below is the python code implementing Dijkstra's Algorithm using adjacency list representation of graphs:

```python
import sys

class Graph():
    def __init__(self, vertices):
        self.V = vertices
        self.graph = [[0 for column in range(vertices)] for row in range(vertices)]

    def printSolution(self, dist):
        print("Vertex \tDistance from Source")
        for node in range(self.V):
            print(node, "\t", dist[node])

    # A utility function to find the vertex with minimum distance value, from the set of vertices not yet included in shortest path tree
    def minDistance(self, dist, sptSet):

        # Initilaize minimum distance for next node
        min = sys.maxsize

        # Search not nearest vertex not in the shortest path tree
        for v in range(self.V):
            if dist[v] < min and sptSet[v] == False:
                min = dist[v]
                min_index = v

        return min_index

    # Function that implements Dijkstra's single source shortest path algorithm for a graph represented using adjacency matrix representation
    def dijkstra(self, src):

        dist = [sys.maxsize] * self.V
        dist[src] = 0
        sptSet = [False] * self.V

        for cout in range(self.V):

            # Pick the minimum distance vertex from the set of vertices not yet processed. u is always equal to src in first iteration
            u = self.minDistance(dist, sptSet)

            # Put the minimum distance vertex in the shotest path tree
            sptSet[u] = True

            # Update dist value of the adjacent vertices of the picked vertex only if the current distance is greater than new distance and the vertex is not in the shotest path tree
            for v in range(self.V):
                if self.graph[u][v] > 0 and sptSet[v] == False and dist[u] + self.graph[u][v] < dist[v]:
                    dist[v] = dist[u] + self.graph[u][v]

        self.printSolution(dist)


# Driver program to test above function
g = Graph(9)
g.graph = [[0, 4, 0, 0, 0, 0, 0, 8, 0],
           [4, 0, 8, 0, 0, 0, 0, 11, 0],
           [0, 8, 0, 7, 0, 4, 0, 0, 2],
           [0, 0, 7, 0, 9, 14, 0, 0, 0],
           [0, 0, 0, 9, 0, 10, 0, 0, 0],
           [0, 0, 4, 14, 10, 0, 2, 0, 0],
           [0, 0, 0, 0, 0, 2, 0, 1, 6],
           [8, 11, 0, 0, 0, 0, 1, 0, 7],
           [0, 0, 2, 0, 0, 0, 6, 7, 0]]

g.dijkstra(0);
```

This script creates a graph object and calls its `dijkstra()` method passing the starting node index (0 based). It then prints out each node along with their respective shortest path lengths from the source node.